# Generated by Django 5.1.4 on 2025-08-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_address', models.CharField(max_length=42)),
                ('candidate_id', models.IntegerField()),
                ('transaction_hash', models.CharField(max_length=66)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
